###
GET http://localhost:8080/list 

### 
POST http://localhost:8080/list 
Content-Type: application/json

{
    "title":"teste", 
    "task": "minha tarefa"
}

###
POST http://localhost:8080/delete 
Content-Type: application/json

{
    "title":"a", 
    "task": "a"
}